= Kieran Potts
:pdf-themesdir: {docdir}/themes
:pdf-theme: cv
:!outline:
:table-caption!:
:nofooter:

:link-linkedin: https://linkedin.com/in/kieranpotts
:link-github: https://github.com/kieranpotts
:link-blog: https://kieranpotts.com/

Staff Software Developer

{link-linkedin}[linkedin.com/in/kieranpotts] • {link-github}[github.com/kieranpotts] • {link-blog}[kieranpotts.com] +
\hello@kieranpotts.com • 07706 130 393 • Bristol, UK

== Specialisations

* Full-stack web application design
* React, Vue, front-end web UIs
* HTTP and GraphQL APIs
* JavaScript, TypeScript, Node.js
* PHP, Laravel

== Certifications

* GitHub Actions

== Selected projects

[%unbreakable]
--
*LexisNexis Risk Solutions* +
Software Developer III, 2024

* Supported the redesign of the company's flagship identity screening service
* Iterated the design of a new API gateway service, written in PHP with Laravel
* Extended back-end services written in a specialist data analytics tool, Enterprise Control Language
* Wrote additional data analysis scripts in Go
* Developed validation services for passports, driving licences, and national insurance numbers
* Maintained 100% code coverage through a combination of unit and integration tests
* Documented complex logic using flowcharts generated by Mermaid
* Implemented monitoring and observability (Grafana, UpTrends)
* Configured CI/CD pipelines (GitHub Actions)

////
NOTES:
ECL is similar in concept to Hadoop's MapReduce programming model. A declarative,
functional, data-oriented, programming language, it enables the processing of big
datasets in parallel across a computer cluster.
////
--

ifdef::full[]
[%unbreakable]
--
*LiveMore Mortgages* +
Technical Lead, 2024

* Planned and coordinated a successful big-bang deployment of a major new feature
* Deployed multiple service updates to AWS, automated via CodeDeploy and GitHub Actions
* Implemented Jira Service Desk with Slack integration to improve customer support management
* Consolidated fragmented technical documentation into a single Confluence space
--
endif::[]

[%unbreakable]
--
*Specsavers* +
Senior Software Developer, 2021 - 2023

* Rebuilt a monolithic business system as a distributed cloud service
* Implemented a micro front-end architecture that supported SPA development across six teams
* Maintained a Vue-based UI component library, documented using Storybook
* Contributed to back-end services written in Java on the Spring Framework
* Implemented a GraphQL API gateway service; consulted on the design of client-server contracts
* Collaborated with business analysts on software requirements specifications and acceptance criteria
* Collaborated with QA engineers on automated system tests using Selenium
* Collaborated with platform engineers on Azure DevOps automation
* Steered a cross-team technical standards alignment group
* Proposed and gathered consensus for better ways of working

////
NOTES:
Socrates is Specsavers' patient management system. The legacy version is a
long-lived desktop Java application. The new version, Socrates Cloud, is a
centralized cloud service, to be incrementally rolled out globally.
////
--

[%unbreakable]
--
*Moorfields Eye Hospital* +
Senior Software Developer, 2021

* Created a statically-generated web front-end complying with WCAG Level AA accessibility standards
* Contributed to a library of custom UI components built with Vue
* Set up automated accessibility tests using aXe and visual regression tests using WebDriverIO
* Conducted manual accessibility testing using assistive technologies such as NVDA
--

[%unbreakable]
--
*TimeTrack* +
Technical Lead, 2020 - 2021

* Coordinated a remote team of contractors and freelancers; oversaw all design and development activities
* Worked closely with the business owner to design the core data processing algorithms
* Established an RFC-style system to document technical proposals and key design decisions
* Implemented a back-end service as a modular monolith, designed for extraction into services
* Took a domain-driven design approach to application architecture
* Prototyped a single-page web application built with React, served by an HTTP API gateway
* Created extensions for Chromium browsers and Firefox, compiled from a single source
* Repurposed a Material Design component library for the UI
* Planned for scalability from the start, eg. denormalization and read-write segregation in database
* Node.js workers were used to leverage multi-threading in the main request-response cycle
* Long-running data processing tasks were queued in a job scheduling system
--


ifdef::history[]
[%unbreakable]
--
.Employment and education history
[cols="1,5"]
|===
|2024 - present |Contract Software Developer
|2021 - 2023    |Senior Software Developer, BJSS
|2017 - 2021    |Software Consultant, Kieran Potts Consultancy Ltd
|2016 - 2017    |Full-Stack Web Developer, Zapmap
|2014 - 2016    |Front-End Web Developer, investUP
|2006 - 2014    |Freelance Web Developer
|2004 - 2005    |Technology Writer, Deputy Editor of PC Plus magazine, Future Publishing
|2001 - 2003    |Staff Writer, ITP (Dubai)
|1998 - 2001    |First-class honours in Human Geography, Leeds University
|===
--
endif::[]
