:pdf-themesdir: {docdir}/themes
:pdf-theme: letter
:!outline:
:nofooter:

////
NOTE: Custom edits to this file, for specific job applications, should not be
committed. To configure Git to ignore changes to this file, run:

  git update-index --assume-unchanged src/letter.adoc

To remove the ignore flag:

  git update-index --no-assume-unchanged src/letter.adoc

To reset working changes to the last commit:

  git checkout HEAD -- src/letter.adoc
////

[.text-right]
Kieran Potts +
\hello@kieranpotts.com +
07706 130 393 +
Bristol, UK

<DD MMM YYYY>

To whom it may concern,

== <Job Title>

I'm writing to express my interest in the above role at <Company Name>.

I have two decades of experience delivering web-based enterprise application
software. I like to work across the whole software development life cycle,
from analysing requirements and drafting specifications, via architectural
design and infrastructure planning, to testing and release. At various times
I've filled the roles of developer, business analyst, technical architect, and
team lead.

I often engage with stakeholders outside of the development teams, for example
collaborating with product managers on technical decisions, and communicating
directly with end users. With a prior career in technology journalism, I'm
good at communicating concepts and translating requirements between the
business and technical domains.

In technical leadership roles I've managed teams, shaped standards, documented
processes, and coached individuals. I've made key design decisions in
large-scale distributed systems, and coordinated the subsequent implementation
across multiple work streams.

Although I'm increasingly engaged in project management, team leadership, and
architectural design, I still like to be hands-on as much as I can. My
computer programming experience is centred on the web platform, but I also have
experience with Java, Python, and Go. I'm effective at switching between
high-level strategies and design, and zooming in on low-level implementation
details.

I prioritise _quality_ in outcomes. I promote industry best practices that are
formed from empirical evidence of what works best, such as test-driven
development, pair programming, continuous integration, and continuous deployment
supported by feature flags. I advocate lightweight change management processes
driven by fast feedback loops, and consensus decision-making in the context of
learning-oriented and psychologically-safe work environments. These methods
and tools are proven to increase the likelihood of successful outcomes in all
kinds of software projects.

Thank you for considering my application.

Regards, +
Kieran Potts
